// src/data.js
export const defaultTracks = [
  { id: "default-001", name: "KR$NA - Joota Japani", url: "/track/KR$NA - Joota Japani.mp3" },
  { id: "default-002", name: "KR$NA - I Guess", url: "/track/KR$NA - I Guess.mp3" },
  { id: "default-003", name: "Hanumankind", url: "/track/Hanumankind.mp3" },
  { id: "default-004", name: "Hanumankind - Run It Up", url: "/track/Hanumankind - Run It Up.mp3" },
  { id: "default-005", name: "LIFE GOES ON - Aleemrk", url: "/track/LIFE GOES ON - aleemrk (Official Audio).mp3" },
  { id: "default-006", name: "KABHI KABHI - Aleemrk", url: "/track/KABHI KABHI - aleemrk (Official Audio).mp3" },
  { id: "default-007", name: "Apocalypse", url: "/track/Apocalypse.mp3" },
  { id: "default-008", name: "Parkha Na", url: "/track/Parkhana.mp3" },
  { id: "default-009", name: "Timro Pratiksa", url: "/track/TimroPratiksa.mp3" },
  { id: "default-010", name: "Sahiba Tere", url: "/track/SahibaSong.mp3" },
  { id: "default-011", name: "Departure - Talha Anjum", url: "/track/Departure Lane - Talha Anjum.mp3" },
  { id: "default-012", name: "HASEEN", url: "/track/HASEEN - TALWIINDER.mp3" },
  { id: "default-013", name: "Slow Dancing In The Dark", url: "/track/Joji - Slow Dancing In The Dark.mp3" },
  { id: "default-014", name: "Pal Pal", url: "/track/Pal Pal.mp3" },
  { id: "default-015", name: "SHOR", url: "/track/SHOR-TalhaAnjummp3" },
  { id: "default-016", name: "kalandar Munawwar Faruqui", url: "/track/Kalandar (feat. Farhan Khan).mp4" },
  { id: "default-017", name: "aleemrk - Cold Hours", url: "/track/aleemrk - Cold Hours (Lyrics).mp3" },
  { id: "default-018", name: "AUR - Tu hai Kaha", url: "/track/AUR - Tu hai kahan.mp3" },
  { id: "default-019", name: "SHOR-TalhaAnjum", url: "/track/SHOR-TalhaAnjum.mp3" },
  { id: "default-020", name: "These Are the Days - Hostel Daze", url: "/track/These Are the Days.mp3" },
  { id: "default-021", name: "Jaa heer ne tainu chod diya", url: "/track/Jaa heer ne tainu chod diya - Raanjhan.mp3" },
  { id: "default-022", name: "XXXTENTACION - the remedy for the broken heart", url: "/track/XXXTENTACION - the remedy for the broken heart (Lyrics).mp3" },
  { id: "default-023", name: "KR$NA - NO CAP", url: "/track/KR$NA - NO CAP (OFFICIAL VIDEO)  KALAMKAAR.mp4" },
  { id: "default-024", name: "Agency - Talha Anjum", url: "/track/Agency - Talha Anjum.mp3" },
  { id: "default-025", name: "Pehle Bhi Main", url: "/track/Pehle Bhi Main (Slowed  Reverb) .mp3" },
  { id: "default-026", name: "Thenkizhakku - Tamil Version", url: "/track/Thenkizhakku - Tamil Song.mp3" },
  { id: "default-027", name: "skechers", url: "/track/skechers.mp3" },


];